### ISSUE TITLE
Can you add me to be able to create branches and Pull Requests?

### ISSUE THREAD

**Issue by cris-pr** [alexoleam/stock_pillar_analysis#1]

**Comment by cris-pr** [comment]
I want to add my fix to the template for you to check and see via a Pull Request.

**Comment by alexoleam** [comment]
> I want to add my fix to the template for you to check and see via a Pull Request.

Hi Cristian,

I have just sent you an invitation as a collaborator for this repository.

Regards!

**Comment by cris-pr** [comment]
Thank you!
